using System.Collections.Generic;

namespace TranslateCSV
{
    /// <summary>Verwaltet alle lokalisierten UI-Texte für DE / EN / FR.</summary>
    public static class Localization
    {
        private static string _lang = "de";

        public static void SetLanguage(string lang)
            => _lang = Strings.ContainsKey(lang) ? lang : "de";

        public static string Get(string key)
            => Strings.TryGetValue(_lang, out var d) && d.TryGetValue(key, out var v) ? v : $"[{key}]";

        private static readonly Dictionary<string, Dictionary<string, string>> Strings = new()
        {
            // ═══════════════════════════════════════════════════════════ DEUTSCH
            ["de"] = new()
            {
                ["WindowTitle"]             = "TranslateCSV 2.0 – Empyrion Übersetzungstool",
                ["LangLabel"]               = "🌐 Sprache:",
                ["Tab_Api"]                 = "🔑  API & Sprachen",
                ["Tab_Files"]               = "📁  Dateien",
                ["Tab_Advanced"]            = "⚙  Erweitert",
                ["Group_ApiKey"]            = "DeepL API-Schlüssel",
                ["Group_Languages"]         = "Spracheinstellungen",
                ["Group_CsvFiles"]          = "CSV-Dateien",
                ["Group_HelperFiles"]       = "Hilfsdateien",
                ["Group_Advanced"]          = "Übersetzungsoptionen",
                ["Group_Log"]               = "Protokoll",
                ["Lbl_ApiKey"]              = "API-Schlüssel:",
                ["Lbl_AccountType"]         = "Kontotyp:",
                ["Lbl_SourceLang"]          = "Quellsprache (CSV):",
                ["Lbl_TargetLang"]          = "Zielsprache (CSV):",
                ["Lbl_DeepLCode"]           = "DeepL-Sprachcode:",
                ["Lbl_InputFile"]           = "Eingabedatei  *:",
                ["Lbl_OutputFile"]          = "Ausgabedatei:",
                ["Lbl_RefFile"]             = "Referenzdatei:",
                ["Lbl_ProtectWords"]        = "Schutzwörter-Datei:",
                ["Lbl_Glossar"]             = "Glossar-Datei:",
                ["Lbl_NewTranslate"]        = "Alles neu übersetzen:",
                ["Lbl_MaxTranslations"]     = "Max. Übersetzungen:",
                ["Lbl_ParallelCalls"]       = "Parallele Aufrufe:",
                ["Radio_Free"]              = "Free-Account (kostenlos, endet auf ':fx')",
                ["Radio_Pro"]               = "Pro-Account (kostenpflichtig)",
                ["Hint_ApiUrl"]             = "💡 Kostenlosen API-Schlüssel erstellen: https://www.deepl.com/pro#developer  (500.000 Zeichen/Monat gratis)",
                ["Hint_LangCodes"]          = "Beispiel: DE = Deutsch, FR = Französisch, ES = Spanisch, IT = Italienisch, RU = Russisch",
                ["Hint_Files"]              = "* = Pflichtfeld  |  Ausgabedatei leer lassen, um die Eingabedatei direkt zu aktualisieren",
                ["Hint_HelperFiles"]        = "Diese Dateien liegen standardmäßig im Programmordner. Leer lassen = Standarddatei verwenden.",
                ["Hint_Unlimited"]          = "(0 = unbegrenzt)",
                ["Hint_Advanced"]           = "💡 Tipp: Starte mit Max. Übersetzungen = 5 zum Testen, bevor du alles übersetzt.",
                ["Btn_Start"]               = "▶  Übersetzung starten",
                ["Btn_Cancel"]              = "✕  Abbrechen",
                ["Status_Ready"]            = "Bereit",
                ["Status_Running"]          = "Übersetzung läuft...",
                ["Status_Cancelling"]       = "Abbruch...",
                ["Tooltip_ApiKey"]          = "Dein persönlicher DeepL API-Schlüssel. Kostenlos registrieren unter deepl.com/pro#developer",
                ["Tooltip_AccountType"]     = "Free-Schlüssel enden auf ':fx', Pro-Schlüssel nicht",
                ["Tooltip_RadioFree"]       = "Kostenloser DeepL-Account: bis 500.000 Zeichen pro Monat gratis",
                ["Tooltip_RadioPro"]        = "Kostenpflichtiger DeepL Pro-Account ohne Zeichenlimit",
                ["Tooltip_ShowKey"]         = "Schlüssel anzeigen / verbergen",
                ["Tooltip_SourceLang"]      = "Spaltenname in der CSV-Datei für die Originalsprache, z.B. 'English'",
                ["Tooltip_TargetLang"]      = "Spaltenname in der CSV-Datei für die Übersetzung, z.B. 'Deutsch'",
                ["Tooltip_DeepLCode"]       = "Sprachkürzel für die DeepL API. Aus der Liste wählen oder direkt eingeben.",
                ["Tooltip_InputFile"]       = "Pflichtfeld: Die CSV-Datei mit den zu übersetzenden Texten",
                ["Tooltip_OutputFile"]      = "Optional: Zieldatei. Leer lassen = Eingabedatei wird überschrieben.",
                ["Tooltip_RefFile"]         = "Optional: Alte CSV als Referenz – bereits übersetzte Texte werden direkt übernommen.",
                ["Tooltip_ProtectWords"]    = "Muster, die NICHT übersetzt werden sollen (z.B. @w4, {PlayerName})",
                ["Tooltip_Glossar"]         = "CSV-Datei mit manuellen Übersetzungen für spielspezifische Begriffe",
                ["Tooltip_Browse"]          = "Datei auswählen",
                ["Tooltip_NewTranslate"]    = "Übersetzt alle Einträge neu, auch wenn bereits eine Übersetzung vorhanden ist",
                ["Tooltip_MaxTranslations"] = "Maximale Anzahl zu übersetzender Einträge. 0 = unbegrenzt.",
                ["Tooltip_ParallelCalls"]   = "Anzahl gleichzeitiger DeepL-API-Aufrufe. Standard: 8",
                ["Msg_MissingInput"]        = "Bitte eine Eingabedatei auswählen (Tab 'Dateien').",
                ["Msg_MissingTargetLang"]   = "Bitte die Zielsprache der CSV angeben, z.B. 'Deutsch' (Tab 'API & Sprachen').",
                ["Msg_MissingDeepLCode"]    = "Bitte den DeepL-Sprachcode angeben, z.B. 'DE' (Tab 'API & Sprachen').",
                ["Msg_MissingTitle"]        = "Fehlende Eingabe",
                ["Msg_Cancelled"]           = "⚠  Übersetzung wurde abgebrochen.",
                ["Msg_CancelRequest"]       = "⚠  Abbruch angefordert – bitte warten...",
                ["Msg_Error"]               = "Fehler",
                ["LogHeader"]               = "TranslateCSV 2.0 – Übersetzung läuft",
            },

            // ═══════════════════════════════════════════════════════════ ENGLISH
            ["en"] = new()
            {
                ["WindowTitle"]             = "TranslateCSV 2.0 – Empyrion Translation Tool",
                ["LangLabel"]               = "🌐 Language:",
                ["Tab_Api"]                 = "🔑  API & Languages",
                ["Tab_Files"]               = "📁  Files",
                ["Tab_Advanced"]            = "⚙  Advanced",
                ["Group_ApiKey"]            = "DeepL API Key",
                ["Group_Languages"]         = "Language Settings",
                ["Group_CsvFiles"]          = "CSV Files",
                ["Group_HelperFiles"]       = "Helper Files",
                ["Group_Advanced"]          = "Translation Options",
                ["Group_Log"]               = "Log",
                ["Lbl_ApiKey"]              = "API Key:",
                ["Lbl_AccountType"]         = "Account type:",
                ["Lbl_SourceLang"]          = "Source language (CSV):",
                ["Lbl_TargetLang"]          = "Target language (CSV):",
                ["Lbl_DeepLCode"]           = "DeepL language code:",
                ["Lbl_InputFile"]           = "Input file  *:",
                ["Lbl_OutputFile"]          = "Output file:",
                ["Lbl_RefFile"]             = "Reference file:",
                ["Lbl_ProtectWords"]        = "Protect words file:",
                ["Lbl_Glossar"]             = "Glossary file:",
                ["Lbl_NewTranslate"]        = "Retranslate all:",
                ["Lbl_MaxTranslations"]     = "Max. translations:",
                ["Lbl_ParallelCalls"]       = "Parallel calls:",
                ["Radio_Free"]              = "Free account (ends with ':fx')",
                ["Radio_Pro"]               = "Pro account (paid)",
                ["Hint_ApiUrl"]             = "💡 Get a free API key at: https://www.deepl.com/pro#developer  (500,000 chars/month free)",
                ["Hint_LangCodes"]          = "Example: DE = German, FR = French, ES = Spanish, IT = Italian, RU = Russian",
                ["Hint_Files"]              = "* = Required  |  Leave output file empty to overwrite the input file directly",
                ["Hint_HelperFiles"]        = "These files are in the program folder by default. Leave empty = use default file.",
                ["Hint_Unlimited"]          = "(0 = unlimited)",
                ["Hint_Advanced"]           = "💡 Tip: Start with Max. translations = 5 to test before translating everything.",
                ["Btn_Start"]               = "▶  Start Translation",
                ["Btn_Cancel"]              = "✕  Cancel",
                ["Status_Ready"]            = "Ready",
                ["Status_Running"]          = "Translation running...",
                ["Status_Cancelling"]       = "Cancelling...",
                ["Tooltip_ApiKey"]          = "Your personal DeepL API key. Register for free at deepl.com/pro#developer",
                ["Tooltip_AccountType"]     = "Free keys end with ':fx', Pro keys do not",
                ["Tooltip_RadioFree"]       = "Free DeepL account: up to 500,000 characters/month free",
                ["Tooltip_RadioPro"]        = "Paid DeepL Pro account without character limit",
                ["Tooltip_ShowKey"]         = "Show / hide key",
                ["Tooltip_SourceLang"]      = "Column name in the CSV for the source language, e.g. 'English'",
                ["Tooltip_TargetLang"]      = "Column name in the CSV for the translation, e.g. 'Deutsch'",
                ["Tooltip_DeepLCode"]       = "Language code for the DeepL API. Select from list or type directly.",
                ["Tooltip_InputFile"]       = "Required: The CSV file with the texts to translate",
                ["Tooltip_OutputFile"]      = "Optional: Output file. Leave empty = input file will be overwritten.",
                ["Tooltip_RefFile"]         = "Optional: Old CSV as reference – existing translations are reused.",
                ["Tooltip_ProtectWords"]    = "Patterns that should NOT be translated (e.g. @w4, {PlayerName})",
                ["Tooltip_Glossar"]         = "CSV file with manual translations for game-specific terms",
                ["Tooltip_Browse"]          = "Select file",
                ["Tooltip_NewTranslate"]    = "Retranslates all entries, even those already translated",
                ["Tooltip_MaxTranslations"] = "Maximum number of entries to translate. 0 = unlimited.",
                ["Tooltip_ParallelCalls"]   = "Number of simultaneous API calls. Default: 8",
                ["Msg_MissingInput"]        = "Please select an input file (Tab 'Files').",
                ["Msg_MissingTargetLang"]   = "Please specify the CSV target language, e.g. 'Deutsch' (Tab 'API & Languages').",
                ["Msg_MissingDeepLCode"]    = "Please enter the DeepL language code, e.g. 'DE' (Tab 'API & Languages').",
                ["Msg_MissingTitle"]        = "Missing input",
                ["Msg_Cancelled"]           = "⚠  Translation was cancelled.",
                ["Msg_CancelRequest"]       = "⚠  Cancel requested – please wait...",
                ["Msg_Error"]               = "Error",
                ["LogHeader"]               = "TranslateCSV 2.0 – Translation running",
            },

            // ═══════════════════════════════════════════════════════════ FRANÇAIS
            ["fr"] = new()
            {
                ["WindowTitle"]             = "TranslateCSV 2.0 – Outil de traduction Empyrion",
                ["LangLabel"]               = "🌐 Langue :",
                ["Tab_Api"]                 = "🔑  API & Langues",
                ["Tab_Files"]               = "📁  Fichiers",
                ["Tab_Advanced"]            = "⚙  Avancé",
                ["Group_ApiKey"]            = "Clé API DeepL",
                ["Group_Languages"]         = "Paramètres de langue",
                ["Group_CsvFiles"]          = "Fichiers CSV",
                ["Group_HelperFiles"]       = "Fichiers auxiliaires",
                ["Group_Advanced"]          = "Options de traduction",
                ["Group_Log"]               = "Journal",
                ["Lbl_ApiKey"]              = "Clé API :",
                ["Lbl_AccountType"]         = "Type de compte :",
                ["Lbl_SourceLang"]          = "Langue source (CSV) :",
                ["Lbl_TargetLang"]          = "Langue cible (CSV) :",
                ["Lbl_DeepLCode"]           = "Code de langue DeepL :",
                ["Lbl_InputFile"]           = "Fichier d'entrée  * :",
                ["Lbl_OutputFile"]          = "Fichier de sortie :",
                ["Lbl_RefFile"]             = "Fichier de référence :",
                ["Lbl_ProtectWords"]        = "Fichier de mots protégés :",
                ["Lbl_Glossar"]             = "Fichier de glossaire :",
                ["Lbl_NewTranslate"]        = "Tout retraduire :",
                ["Lbl_MaxTranslations"]     = "Traductions max. :",
                ["Lbl_ParallelCalls"]       = "Appels parallèles :",
                ["Radio_Free"]              = "Compte gratuit (se termine par ':fx')",
                ["Radio_Pro"]               = "Compte Pro (payant)",
                ["Hint_ApiUrl"]             = "💡 Créer une clé API gratuite : https://www.deepl.com/pro#developer  (500 000 caractères/mois gratuits)",
                ["Hint_LangCodes"]          = "Exemple : DE = Allemand, FR = Français, ES = Espagnol, IT = Italien, RU = Russe",
                ["Hint_Files"]              = "* = Obligatoire  |  Laisser le fichier de sortie vide pour mettre à jour le fichier d'entrée",
                ["Hint_HelperFiles"]        = "Ces fichiers sont dans le dossier du programme par défaut. Laisser vide = utiliser le fichier par défaut.",
                ["Hint_Unlimited"]          = "(0 = illimité)",
                ["Hint_Advanced"]           = "💡 Conseil : Commencez avec Traductions max. = 5 pour tester avant de tout traduire.",
                ["Btn_Start"]               = "▶  Démarrer la traduction",
                ["Btn_Cancel"]              = "✕  Annuler",
                ["Status_Ready"]            = "Prêt",
                ["Status_Running"]          = "Traduction en cours...",
                ["Status_Cancelling"]       = "Annulation...",
                ["Tooltip_ApiKey"]          = "Votre clé API DeepL personnelle. Inscription gratuite sur deepl.com/pro#developer",
                ["Tooltip_AccountType"]     = "Les clés gratuites se terminent par ':fx', pas les clés Pro",
                ["Tooltip_RadioFree"]       = "Compte DeepL gratuit : jusqu'à 500 000 caractères/mois gratuits",
                ["Tooltip_RadioPro"]        = "Compte DeepL Pro payant sans limite de caractères",
                ["Tooltip_ShowKey"]         = "Afficher / masquer la clé",
                ["Tooltip_SourceLang"]      = "Nom de la colonne dans le CSV pour la langue source, ex. 'English'",
                ["Tooltip_TargetLang"]      = "Nom de la colonne dans le CSV pour la traduction, ex. 'Deutsch'",
                ["Tooltip_DeepLCode"]       = "Code de langue pour l'API DeepL. Choisir dans la liste ou saisir directement.",
                ["Tooltip_InputFile"]       = "Obligatoire : Le fichier CSV avec les textes à traduire",
                ["Tooltip_OutputFile"]      = "Optionnel : Fichier de sortie. Vide = le fichier d'entrée sera écrasé.",
                ["Tooltip_RefFile"]         = "Optionnel : Ancien CSV comme référence – les traductions existantes sont réutilisées.",
                ["Tooltip_ProtectWords"]    = "Motifs qui NE doivent PAS être traduits (ex. @w4, {PlayerName})",
                ["Tooltip_Glossar"]         = "Fichier CSV avec des traductions manuelles pour les termes spécifiques au jeu",
                ["Tooltip_Browse"]          = "Sélectionner un fichier",
                ["Tooltip_NewTranslate"]    = "Retraduit toutes les entrées, même celles déjà traduites",
                ["Tooltip_MaxTranslations"] = "Nombre maximum d'entrées à traduire. 0 = illimité.",
                ["Tooltip_ParallelCalls"]   = "Nombre d'appels API simultanés. Par défaut : 8",
                ["Msg_MissingInput"]        = "Veuillez sélectionner un fichier d'entrée (onglet 'Fichiers').",
                ["Msg_MissingTargetLang"]   = "Veuillez indiquer la langue cible du CSV, ex. 'Deutsch' (onglet 'API & Langues').",
                ["Msg_MissingDeepLCode"]    = "Veuillez entrer le code de langue DeepL, ex. 'DE' (onglet 'API & Langues').",
                ["Msg_MissingTitle"]        = "Saisie manquante",
                ["Msg_Cancelled"]           = "⚠  La traduction a été annulée.",
                ["Msg_CancelRequest"]       = "⚠  Annulation demandée – veuillez patienter...",
                ["Msg_Error"]               = "Erreur",
                ["LogHeader"]               = "TranslateCSV 2.0 – Traduction en cours",
            },
        };
    }
}
